container:
  image: node:latest

sut_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  sut_script: npm run test
