container:
  image: node:latest

test_task:
  auto_cancellation: $CIRRUS_BRANCH != 'master' && $CIRRUS_BRANCH != 'development'
  only_if: $CIRRUS_PR != ''
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  script: npm run test
