container:
  image: node:latest

unit_test_task:
  container:
    cpu: 1
    memory: 1G
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  unit_test_script: npm test
    
